services:
- type: web
  name: line-bot-python-flask
  env: python
  repo: https://github.com/pollop123/drinkControl
  buildCommand: cd examples/flask-echo;pip install gunicorn -r requirements.txt
  startCommand: cd examples/flask-echo;gunicorn app:app
  plan: free
  autoDeploy: false
  envVars:
  - key: JZ5sx/p8CYJfDpjmh9oWodRa1F4M67xaOafyNz3jIGceUpW/kdySl2UeAtpe6LWUT9RpXIeAT6RGSPUEKT3h+k3/MDEEdPbNXWy85/HgaXc1AQYkh61q46IinVSJafTYCKLjXktH6pJ4D399HWolEwdB04t89/1O/w1cDnyilFU=
    sync: false
  - key: 49e2923a64ddfe4a8b2f8310496e78fa
    sync: false
# - type: web
#   name: line-bot-python-flask-with-handler
#   env: python
#   repo: https://github.com/line/line-bot-sdk-python.git
#   buildCommand: cd examples/flask-echo;pip install gunicorn -r requirements.txt
#   startCommand: cd examples/flask-echo;gunicorn app_with_handler:app
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
# - type: web
#   name: line-bot-python-flask-kitchensink
#   env: python
#   repo: https://github.com/line/line-bot-sdk-python.git
#   buildCommand: cd examples/flask-kitchensink;pip install gunicorn -r requirements.txt
#   startCommand: cd examples/flask-kitchensink;gunicorn app:app
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
# - type: web
#   name: line-bot-python-simple-server
#   env: python
#   repo: https://github.com/line/line-bot-sdk-python.git
#   buildCommand: cd examples/simple-server-echo;pip install -r requirements.txt
#   startCommand: cd examples/simple-server-echo;python app.py
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
# - type: web
#   name: line-bot-python-aiohttp
#   env: python
#   repo: https://github.com/line/line-bot-sdk-python.git
#   buildCommand: cd examples/aiohttp-echo;pip install -r requirements.txt
#   startCommand: cd examples/aiohttp-echo;python app.py
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
